version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=jardam_kolu
      - USE_DOCKER=yes
      - DISQUSSHORTNAME=jardam-kolu
      - GOOGLE_CAPTCHA_SITE_KEY
      - GOOGLE_CAPTCHA_SECRET_KEY
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=jardam_kolu

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"


  redis:
    image: redis:3.0

  celeryworker:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat.sh

